openapi: 3.0.0
info:
  title: public api
  version: 1.0.0
servers:
  - url: https://130.162.195.228
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
paths:
  /mhs714220014/login:
    post:
      tags:
        - default
      summary: login
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                username: wafid
                password: admin12345
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /mhs714220014/lregis:
    post:
      tags:
        - default
      summary: regis
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                username: adzka
                password: admin123456
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /mhs714220014/matakuliah:
    get:
      tags:
        - default
      summary: get all matakuliah
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    post:
      tags:
        - default
      summary: post matakuliah
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                id: 3
                matakuliah: Inggris
                dosen: Agung
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /mhs714220014/matakuliah/3:
    put:
      tags:
        - default
      summary: put matakuliah
      requestBody:
        content: {}
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    delete:
      tags:
        - default
      summary: delete matakuliah
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /mhs714220014/mahasiswa/714220014:
    get:
      tags:
        - default
      summary: get mahasiswa by id
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    put:
      tags:
        - default
      summary: put mahasiswa
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                npm: '714220014'
                nama: Wafid Adzka
                kelas: D4TI2A
                alamat: Cimindi
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /mhs714220014/mahasiswa:
    get:
      tags:
        - default
      summary: get all mahasiswa
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    post:
      tags:
        - default
      summary: post mahasiswa
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                npm: '714220014'
                nama: Fathya
                kelas: D4TI2A
                alamat: Cimahi
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /mhs714220014/mahasiswa/714220013:
    delete:
      tags:
        - default
      summary: delete mahasiswa
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}